# Render Blueprint for deploying the backend as a Web Service
services:
  - type: web
    name: sahara-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://sahara-mental-wellness.vercel.app
      - key: GEMINI_API_KEY
        sync: false




